### ISSUE TITLE
enable:false = default? Need Clarification

### ISSUE THREAD

**Issue by AustinTylerDean** [mainsail-crew/sonar#19]
### Is your feature request related to a problem? Please describe

I can't call this a bug, because I'm not sure of the intention. I had a borked install previously (all my fault) but recently revisited sonar to get it up and running. Going through the install again and correcting the problems I caused earlier, I find the config file with the default of enable: false. Is this by intention? Clearly mentioned in the readme is "You don't need to change the config file".

### Describe the solution you'd like

I'd like more info on this as the default if it is designed that way. It is confusing from 10,000 ft.

### Additional information

I appreciate your time in making this, thank you very much.

**Comment by meteyou** [comment]
Yes, exactly. This is intentional because not everyone has issues with Wi-Fi. Especially for users with an Ethernet connection, enabling it could cause other problems. That's why Sonar is disabled by default.
