### ISSUE TITLE
Fails if device does not have eth

### ISSUE THREAD

**Issue by luigi311** [mainsail-crew/sonar#3]
### What happened

Fails to run due to /sys/class/net/eth0/operstate not existing on devices that do not have ethernet such as the pi zero 2 w. Looking at the journalctl -u sonar it outputs the following error cat: /sys/class/net/eth0/operstate: No such file or directory

### What did you expect to happen

journalctl reports no errors on fresh boot

### How to reproduce

enable sonar on raspberry pi zero 2 w

### Additional information

Apr 28 09:50:26 mainsail systemd[1]: Starting Sonar - A WiFi Keepalive daemon...
Apr 28 09:50:26 mainsail systemd[1]: Started Sonar - A WiFi Keepalive daemon.
Apr 28 09:50:27 mainsail sonar[614]: Sonar - A WiFi Keepalive daemon
Apr 28 09:50:28 mainsail sonar[633]: Version: v0.0.1
Apr 28 09:50:28 mainsail sonar[638]: Prepare Startup ...
Apr 28 09:50:28 mainsail sonar[643]: INFO: Checking Dependencys
Apr 28 09:50:29 mainsail sonar[660]: Dependency: 'logger' found in /usr/bin/logger.
Apr 28 09:50:29 mainsail sonar[590]: cat: /sys/class/net/eth0/operstate: No such file or directory

**Comment by luigi311** [comment]
worked around this by changing the lib/core.sh check_eth_con function to the following though not sure if you want to go with something else.

```
   if [ -f "/sys/class/net/eth0/operstate" ]; then
        if [ "$(cat /sys/class/net/eth0/operstate)" == "up" ]; then
            log_msg "WARN: Connected via ethernet, please disable service ..."
            log_msg "Stopping sonar.service till next reboot ..."
            systemctl stop sonar.service
        fi
   fi
```

**Comment by KwadFan** [comment]
Should be fixed with commit https://github.com/mainsail-crew/sonar/commit/0afc14b9b8b6e438eb449029b2df8f2a5eed42f1

Regards
